apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api-service
  template:
    metadata:
      labels:
        app: product-api-service
    spec:
      containers:
      - name: product-api-service
        image: aniketphadatare/product-api-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"    
        - name: BPL_JVM_HEAD_ROOM
          value: "2"  
        - name: BPL_JVM_LOADED_CLASS_COUNT
          value: "35"  
        - name: BPL_JVM_THREAD_COUNT
          value: "10"  
        - name: JAVA_OPTS
          value: >-
                -XX:ReservedCodeCacheSize=40M
                -XX:MaxMetaspaceSize=60M
                -Xlog:gc
                -Xms34m
                -Xmx40m
                -Xss256k
                -XX:MaxRAM=150M

