apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 8082
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: product-api-service
  externalIPs:
    - 3.0.99.166